### ISSUE TITLE
ERROR: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MinjiaLU** [Illumina/Nirvana#78] opened 2022-06-06 07:51 UTC
ERROR: Object reference not set to an instance of an object.

**Comment by heseber** [comment] 2022-06-13 10:20
This is a duplicate of #79, and although this report is slightly oder, #79 provides more details.

**Comment by rajatshuvro** [comment] 2022-06-14 18:39
Issue has been fixed in the 3.18.1 release.

**Closed by rajatshuvro** 2022-06-14 18:39 UTC
